# Generated by Django 4.2.6 on 2023-10-19 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('active_investment', models.IntegerField(default=0)),
                ('pending_withdraw', models.IntegerField(default=0)),
                ('Total_earnings', models.IntegerField(default=0)),
                ('last_deposit', models.IntegerField(default=0)),
                ('last_withdraw', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
