# Generated by Django 4.2.6 on 2023-10-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='channel',
            field=models.CharField(choices=[('BTC', 'BTC'), ('USDT', 'USDT')], default='BTC', max_length=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
